/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package KodigoNiKerbeh;

import java.sql.*;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Asus
 */
public class JInternalFrameHistory extends javax.swing.JInternalFrame {
    Connection connection;
    /**
     * Creates new form JInternalFrameHistory
     */
    public JInternalFrameHistory() {
        initComponents();
        createConnection();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jPanelDashboard = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransactionHistory = new javax.swing.JTable();

        jToolBar1.setRollover(true);

        jPanelDashboard.setBackground(new java.awt.Color(253, 187, 180));

        jTableTransactionHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Time Processed", "Quantity Sold", "Total Revenue"
            }
        ));
        jScrollPane1.setViewportView(jTableTransactionHistory);

        jPanelDashboard.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDashboard)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDashboard)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void createConnection(){
        String url = "jdbc:mysql://localhost:3306/pos";
        String user = "root";
        String password = "Hoshimachi0322";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection(url, user, password);
            System.out.println("Database Connected Successfully");
        } catch (ClassNotFoundException e){
            System.out.println("MySQL Driver not found!");
            e.printStackTrace();
        } catch (SQLException e){
            System.out.println("Connection Failed!");
            e.printStackTrace();
        }
    }
    
    private void fillTable(){
        DefaultTableModel model = (DefaultTableModel) jTableTransactionHistory.getModel();
        
        model.setRowCount(0);
        try{
            String sql = "SELECT count(*) FROM transactions";
            PreparedStatement ps = connection.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            rs.next();
            int rows = rs.getInt(1);
            
            for (int i = 1; i <= rows; i++) {
                sql = "select idtransaction, transaction_date from transactions, transaction_items where idtransaction = " + i;
                ps = connection.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.next();
                
                int id = rs.getInt(1);
                String date = rs.getString(2);
                
                sql = "SELECT transaction_item_quantity, transaction_item_price from transaction_items where fk_idtransaction =" + i;
                int quantity = 0;
                double revenue = 0;
                
                ps = connection.prepareStatement(sql);
                rs = ps.executeQuery();
                
                DecimalFormat df = new DecimalFormat("#.##");
                
                while(rs.next()){
                    quantity += rs.getInt(1);
                    
                    System.out.println(quantity);
                    
                    revenue += rs.getDouble(2) * rs.getInt(1);
                }
                
                model.addRow(new Object[]{id,date,quantity,df.format(revenue)});
            }
            
        }catch(SQLException e){
            System.out.println(e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancel1;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonConfirm1;
    private javax.swing.JButton jButtonEnter;
    private javax.swing.JButton jButtonEnter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane jPanelDashboard;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableProducts;
    private javax.swing.JTable jTableProducts1;
    private javax.swing.JTable jTableTransactionHistory;
    private javax.swing.JTextArea jTextAreaInvoice;
    private javax.swing.JTextArea jTextAreaInvoice1;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldAmount1;
    private javax.swing.JTextField jTextFieldChange;
    private javax.swing.JTextField jTextFieldChange1;
    private javax.swing.JTextField jTextFieldPayment;
    private javax.swing.JTextField jTextFieldPayment1;
    private javax.swing.JTextField jTextFieldProductID;
    private javax.swing.JTextField jTextFieldProductID1;
    private javax.swing.JTextField jTextFieldProductName;
    private javax.swing.JTextField jTextFieldProductName1;
    private javax.swing.JTextField jTextFieldSubtotal;
    private javax.swing.JTextField jTextFieldSubtotal1;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldTotal1;
    private javax.swing.JTextField jTextFieldVAT;
    private javax.swing.JTextField jTextFieldVAT1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
