/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KodigoNiKerbeh;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class JFrameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDashboard
     */
    public JFrameDashboard() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }
    
    public JFrameDashboard(String UserLogin){
        initComponents();
        if (UserLogin == "admin"){
            JOptionPane.showMessageDialog(this, "Hello Admin");
        }else{
            JOptionPane.showMessageDialog(this, "Hello Cashier");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonTransaction = new javax.swing.JButton();
        jButtonInventory = new javax.swing.JButton();
        jButtonAccount = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jPanelDashboard = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jToolBar1.setBackground(new java.awt.Color(253, 187, 180));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        jButtonTransaction.setBackground(new java.awt.Color(241, 157, 145));
        jButtonTransaction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/120px-Goldenglow_icon.png"))); // NOI18N
        jButtonTransaction.setText("Transaction");
        jButtonTransaction.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTransaction.setFocusable(false);
        jButtonTransaction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTransaction.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonTransaction.setPreferredSize(new java.awt.Dimension(90, 50));
        jButtonTransaction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransactionActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonTransaction);

        jButtonInventory.setBackground(new java.awt.Color(241, 157, 145));
        jButtonInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/120px-Goldenglow_icon.png"))); // NOI18N
        jButtonInventory.setText("Inventory");
        jButtonInventory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonInventory.setFocusable(false);
        jButtonInventory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonInventory.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonInventory.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventoryActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonInventory);

        jButtonAccount.setBackground(new java.awt.Color(241, 157, 145));
        jButtonAccount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/120px-Goldenglow_icon.png"))); // NOI18N
        jButtonAccount.setText("Account");
        jButtonAccount.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAccount.setFocusable(false);
        jButtonAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAccount.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccountActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonAccount);

        jButtonLogout.setBackground(new java.awt.Color(241, 157, 145));
        jButtonLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/120px-Goldenglow_icon.png"))); // NOI18N
        jButtonLogout.setText("Logout");
        jButtonLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLogout.setFocusable(false);
        jButtonLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonLogout.setMaximumSize(new java.awt.Dimension(80, 80));
        jButtonLogout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonLogout);

        jPanelDashboard.setBackground(new java.awt.Color(255, 240, 224));

        javax.swing.GroupLayout jPanelDashboardLayout = new javax.swing.GroupLayout(jPanelDashboard);
        jPanelDashboard.setLayout(jPanelDashboardLayout);
        jPanelDashboardLayout.setHorizontalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        jPanelDashboardLayout.setVerticalGroup(
            jPanelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDashboard))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
            .addComponent(jPanelDashboard)
        );

        pack();
    }// </editor-fold>                        

    private void jButtonTransactionActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        jPanelDashboard.removeAll();
        try{
            JInternalFrameTransaction j = new JInternalFrameTransaction();
            
            jPanelDashboard.add(j);
            j.setVisible(true);
            jPanelDashboard.moveToFront(j);
            jPanelDashboard.setSize(jPanelDashboard.getWidth(), jPanelDashboard.getHeight());
            jPanelDashboard.setLocation(0, 0);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }                                                  

    private void jButtonAccountActionPerformed(java.awt.event.ActionEvent evt) {                                               
        jPanelDashboard.removeAll();
        JInternalFrameAccount acc = new JInternalFrameAccount();
        jPanelDashboard.add(acc);
        
        acc.setVisible(true);
    }                                              

    private void jButtonInventoryActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        jPanelDashboard.removeAll();
        JInternalFrameInventory inventory = new JInternalFrameInventory();
        jPanelDashboard.add(inventory);
        
        inventory.setVisible(true);
        //jPanelDashboard.moveToFront(inventory);
    }                                                

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                              
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        
        this.dispose();
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAccount;
    private javax.swing.JButton jButtonInventory;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonTransaction;
    private javax.swing.JDesktopPane jPanelDashboard;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration                   
}
